[project]
name = "hw3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christian-Holenweger", email = "cholenweger2022@fau.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-experimental>=0.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
]

[project.scripts]
hw3 = "hw3:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
